Repository kookmin-sw/capstone-2023-09, pull requests merged in 2023-05, with the labels that each got.

#167 feat: 프록시 서버 삭제
  src/front-end/timepay-admin/package.json
  src/front-end/timepay-admin/src/api/request.ts
  src/front-end/timepay-front/package.json
  src/front-end/timepay-front/src/api/request.ts
  src/front-end/timepay-front/src/pages/JoinPage/JoinPage.tsx
  src/front-end/timepay-front/src/pages/MyEditPage/MyEditPage.tsx
  src/front-end/timepay-front/src/pages/MyPage/MyPage.tsx
Labels: ✨ feat, 🧶 chore, 🐍 fix

#180 [사용자] 내 봉사활동 기록 페이지 UI 개발
  src/front-end/timepay-front/src/App.tsx
  src/front-end/timepay-front/src/api/interfaces/IVolunteer.ts
  src/front-end/timepay-front/src/api/urls.ts
  src/front-end/timepay-front/src/pages/MyVolunteerPage/MyVolunteerPage.styles.tsx
  src/front-end/timepay-front/src/pages/MyVolunteerPage/MyVolunteerPage.tsx
  src/front-end/timepay-front/src/pages/MyVolunteerPage/index.ts
  src/front-end/timepay-front/src/pages/index.ts
  src/front-end/timepay-front/src/utils/paths.ts
Labels: 💄 design

#183 [사용자] 인증서 지급 화면 UI 추가
  src/front-end/timepay-front/src/App.tsx
  src/front-end/timepay-front/src/api/interfaces/IVolunteer.ts
  src/front-end/timepay-front/src/pages/VolunteerCertificationPaymentPage/VolunteerCertificationPaymentPage.styles.tsx
  src/front-end/timepay-front/src/pages/VolunteerCertificationPaymentPage/VolunteerCertificationPaymentPage.tsx
  src/front-end/timepay-front/src/pages/VolunteerCertificationPaymentPage/index.ts
  src/front-end/timepay-front/src/pages/index.ts
  src/front-end/timepay-front/src/utils/device.ts
  src/front-end/timepay-front/src/utils/paths.ts
Labels: 💄 design

#176 [관리자] 신고관리 기능 연결
  src/front-end/timepay-admin/src/api/hooks/report.ts
  src/front-end/timepay-admin/src/api/interfaces/IReport.ts
  src/front-end/timepay-admin/src/api/urls.ts
  src/front-end/timepay-admin/src/components/ReportDetailModal/ReportDetailModal.tsx
  src/front-end/timepay-admin/src/components/ReportSearchForm/ReportSearchForm.styles.tsx
  src/front-end/timepay-admin/src/components/ReportSearchForm/ReportSearchForm.tsx
  src/front-end/timepay-admin/src/components/ReportTable/ReportTable.tsx
  src/front-end/timepay-admin/src/interfaces/ReportItem.ts
  src/front-end/timepay-admin/src/pages/ReportManagement/ReportManagementPage.tsx
  src/front-end/timepay-admin/src/states/reportSearchState.ts
Labels: ✨ feat, 🔧 refactor

#192 [관리자] 댓글 관리 화면 수정
  src/front-end/timepay-admin/src/api/hooks/comment.ts
  src/front-end/timepay-admin/src/api/interfaces/IComment.ts
  src/front-end/timepay-admin/src/components/CommentSearchForm/CommentSearchForm.tsx
  src/front-end/timepay-admin/src/components/CommentTable/CommentTable.tsx
  src/front-end/timepay-admin/src/states/commentSearchState.ts
  src/front-end/timepay-admin/src/utils/pagination.ts
Labels: 🧶 chore, 🐍 fix

#201 [사용자] 홈화면 ui 수정, 카테고리 api 연결
  src/front-end/timepay-front/src/api/hooks/category.ts
  src/front-end/timepay-front/src/api/interfaces/ICategory.ts
  src/front-end/timepay-front/src/api/urls.ts
  src/front-end/timepay-front/src/assets/images/icons/timepay-character-logo.svg
  src/front-end/timepay-front/src/components/BaseLayout/BaseLayout.styles.tsx
  src/front-end/timepay-front/src/components/BaseLayout/BaseLayout.tsx
  src/front-end/timepay-front/src/pages/AgencySignInPage/AgencySignInPage.tsx
  src/front-end/timepay-front/src/pages/HomePage/HomePage.styles.tsx
  src/front-end/timepay-front/src/pages/HomePage/HomePage.tsx
  src/front-end/timepay-front/src/styles/constants/colors.ts
  src/front-end/timepay-front/src/styles/constants/tabStyle.ts
Labels: 💄 design, ✨ feat

#202 [사용자] 내 프로필 api 변경 및 프로필 수정 화면 디자인 수정
  src/front-end/timepay-front/src/api/urls.ts
  src/front-end/timepay-front/src/pages/MyEditPage/MyEditPage.tsx
  src/front-end/timepay-front/src/pages/MyPage/MyPage.tsx
Labels: 💄 design, 🧶 chore, 🐍 fix

#204 design: 푸터 버튼 변경, 홈화면 헤더 변경
  src/front-end/timepay-front/src/assets/images/icons/activity-record.svg
  src/front-end/timepay-front/src/assets/images/icons/home.svg
  src/front-end/timepay-front/src/assets/images/icons/plus-post.svg
  src/front-end/timepay-front/src/assets/images/icons/write-board.svg
  src/front-end/timepay-front/src/components/BaseLayout/BaseLayout.tsx
  src/front-end/timepay-front/src/components/MainFooter/MainFooter.styles.tsx
  src/front-end/timepay-front/src/components/MainFooter/MainFooter.tsx
Labels: 💄 design

#208 [사용자] 검색 화면 ui 수정
  src/front-end/timepay-front/src/components/SearchHeader/SearchHeader.tsx
  src/front-end/timepay-front/src/components/SimplePostCard/SimplePostCard.styles.tsx
  src/front-end/timepay-front/src/components/SimplePostCard/SimplePostCard.tsx
  src/front-end/timepay-front/src/styles/constants/customTheme.ts
Labels: 💄 design, 🧶 chore

#209 chore: 자동 로그인 불가 처리
  src/front-end/timepay-front/src/pages/LoginPage/LoginPage.tsx
Labels: 🧶 chore

#211 [사용자] 관심분야 알림 화면 UI
  src/front-end/timepay-front/src/App.tsx
  src/front-end/timepay-front/src/pages/CategorySelectPage/CategorySelectPage.styles.tsx
  src/front-end/timepay-front/src/pages/CategorySelectPage/CategorySelectPage.tsx
  src/front-end/timepay-front/src/pages/JoinPage/JoinPage.tsx
  src/front-end/timepay-front/src/pages/MyPage/MyPage.tsx
  src/front-end/timepay-front/src/states/categorySelect.ts
  src/front-end/timepay-front/src/utils/paths.ts
Labels: 💄 design, ✨ feat

#222 [관리자] 공지 작성 form data로 보내도록 수정
  src/front-end/timepay-admin/src/api/hooks/notification.ts
  src/front-end/timepay-admin/src/api/request.ts
  src/front-end/timepay-admin/src/api/urls.ts
  src/front-end/timepay-admin/src/components/PushAddModal/PushAddModal.tsx
Labels: 🧶 chore, 🐍 fix

#221 [사용자] 폰트 크기 조절 버튼 연결, 훅 추가
  src/front-end/timepay-front/src/assets/images/icons/modify-font-size-big.svg
  src/front-end/timepay-front/src/assets/images/icons/modify-font-size-small.svg
  src/front-end/timepay-front/src/components/MainFooter/MainFooter.tsx
  src/front-end/timepay-front/src/hooks/post.ts
  src/front-end/timepay-front/src/hooks/useFontSize.ts
  src/front-end/timepay-front/src/pages/HomePage/HomePage.styles.tsx
  src/front-end/timepay-front/src/pages/HomePage/HomePage.tsx
  src/front-end/timepay-front/src/states/uiState.ts
Labels: 💄 design, ✨ feat

#241 [관리자] 게시글 관리 페이지 기능 연결
  src/front-end/timepay-admin/src/api/hooks/boards.ts
  src/front-end/timepay-admin/src/api/interfaces/IBoard.ts
  src/front-end/timepay-admin/src/api/interfaces/IPost.ts
  src/front-end/timepay-admin/src/api/urls.ts
  src/front-end/timepay-admin/src/components/PostDetailModal/PostDetailModal.tsx
  src/front-end/timepay-admin/src/components/PostHandleModal/PostHandleModal.tsx
  src/front-end/timepay-admin/src/components/PostSearchForm/PostSearchForm.tsx
  src/front-end/timepay-admin/src/components/PostTable/PostTable.tsx
  src/front-end/timepay-admin/src/pages/PostManagement/PostManagementPage.tsx
  src/front-end/timepay-admin/src/states/boardSearchState.ts
  src/front-end/timepay-admin/src/utils/board.ts
Labels: ✨ feat

#245 fix: 비밀번호 변경 오류 수정
  src/front-end/timepay-admin/src/pages/PasswordEdit/PasswordEditPage.tsx
Labels: 🐍 fix

#246 chore: 관리자 컬럼 수정
  src/front-end/timepay-admin/src/api/interfaces/IAdmin.ts
  src/front-end/timepay-admin/src/components/AdminAdd/AdminAdd.tsx
  src/front-end/timepay-admin/src/components/AdminMainTable/AdminMainTable.tsx
Labels: 🧶 chore

#247 [사용자] 게시글 검색화면 기능 연결
  src/front-end/timepay-front/package.json
  src/front-end/timepay-front/src/api/hooks/board.ts
  src/front-end/timepay-front/src/api/interfaces/IPost.ts
  src/front-end/timepay-front/src/api/urls.ts
  src/front-end/timepay-front/src/assets/images/icons/volunteer-badge.svg
  src/front-end/timepay-front/src/components/ActivityPostCard/ActivityPostCard.tsx
  src/front-end/timepay-front/src/components/AnotherUserProfileDrawer/AnotherUserProfileDrawer.tsx
  src/front-end/timepay-front/src/components/BaseLayout/BaseLayout.styles.tsx
  src/front-end/timepay-front/src/components/PostStatusTag/PostStatusTag.tsx
  src/front-end/timepay-front/src/components/PostTypeTag/PostTypeTag.tsx
  src/front-end/timepay-front/src/components/SearchHeader/SearchHeader.styles.tsx
  src/front-end/timepay-front/src/components/SearchHeader/SearchHeader.tsx
  src/front-end/timepay-front/src/components/SimplePostCard/SimplePostCard.styles.tsx
  src/front-end/timepay-front/src/components/SimplePostCard/SimplePostCard.tsx
  src/front-end/timepay-front/src/pages/ActivityRecordPage/ActivityRecordPage.tsx
  src/front-end/timepay-front/src/pages/HomePage/HomePage.styles.tsx
  src/front-end/timepay-front/src/pages/HomePage/HomePage.tsx
  src/front-end/timepay-front/src/pages/SearchPage/SearchPage.styles.tsx
  src/front-end/timepay-front/src/pages/SearchPage/SearchPage.tsx
  src/front-end/timepay-front/src/states/boardSearch.ts
  src/front-end/timepay-front/src/states/uiState.ts
  src/front-end/timepay-front/src/utils/board.ts
  src/front-end/timepay-front/yarn.lock
Labels: 💄 design, ✨ feat, 🧶 chore, 🔧 refactor

#252 [관리자] 문의 관리기능 연결
  src/front-end/timepay-admin/src/App.tsx
  src/front-end/timepay-admin/src/api/hooks/inquiry.ts
  src/front-end/timepay-admin/src/api/interfaces/IInquiry.ts
  src/front-end/timepay-admin/src/api/interfaces/IQna.ts
  src/front-end/timepay-admin/src/api/urls.ts
  src/front-end/timepay-admin/src/components/BaseLayout/BaseLayout.tsx
  src/front-end/timepay-admin/src/components/InquiryTable/InquiryTable.styles.tsx
  src/front-end/timepay-admin/src/components/InquiryTable/InquiryTable.tsx
  src/front-end/timepay-admin/src/components/InquiryTable/index.ts
  src/front-end/timepay-admin/src/components/QnADetailModal/QnADetailModal.styles.ts
  src/front-end/timepay-admin/src/components/QnADetailModal/QnADetailModal.tsx
  src/front-end/timepay-admin/src/components/QnADetailModal/index.ts
  src/front-end/timepay-admin/src/components/QnASearchForm/QnASearchForm.tsx
  src/front-end/timepay-admin/src/components/QnATable/QnATable.tsx
  src/front-end/timepay-admin/src/components/QnATable/index.ts
  src/front-end/timepay-admin/src/pages/InquiryDetailManagement/InquiryDetailManagement.tsx
  src/front-end/timepay-admin/src/pages/InquiryDetailManagement/InquiryDetailManagementPage.style.tsx
  src/front-end/timepay-admin/src/pages/InquiryDetailManagement/index.ts
  src/front-end/timepay-admin/src/pages/InquiryManagement/InquiryManagementPage.styles.tsx
  src/front-end/timepay-admin/src/pages/InquiryManagement/InquiryManagementPage.tsx
  src/front-end/timepay-admin/src/pages/InquiryManagement/index.ts
  src/front-end/timepay-admin/src/pages/QnAManagement/QnAManagementPage.tsx
  src/front-end/timepay-admin/src/pages/QnAManagement/index.ts
  src/front-end/timepay-admin/src/pages/index.ts
  src/front-end/timepay-admin/src/states/inquirySearchState.ts
  src/front-end/timepay-admin/src/utils/paths.ts
Labels: ✨ feat, 🔧 refactor

#254 [사용자] 활동 기록 화면 기능 연결
  src/front-end/timepay-front/src/api/hooks/user.ts
  src/front-end/timepay-front/src/api/interfaces/IComment.ts
  src/front-end/timepay-front/src/api/interfaces/ICommon.ts
  src/front-end/timepay-front/src/api/interfaces/IUser.ts
  src/front-end/timepay-front/src/api/urls.ts
  src/front-end/timepay-front/src/components/ActivityCommentCard/ActivityCommentCard.styles.tsx
  src/front-end/timepay-front/src/components/ActivityCommentCard/ActivityCommentCard.tsx
  src/front-end/timepay-front/src/components/ActivityPostCard/ActivityPostCard.styles.tsx
  src/front-end/timepay-front/src/components/ActivityPostCard/ActivityPostCard.tsx
  src/front-end/timepay-front/src/pages/ActivityRecordPage/ActivityRecordPage.styles.tsx
  src/front-end/timepay-front/src/pages/ActivityRecordPage/ActivityRecordPage.tsx
Labels: ✨ feat, 🧶 chore

#256 [사용자] 로그인, 로그아웃, 내 봉사활동 기록 메뉴 링크 추가, 기관 여부에 따라 푸터 수정
  src/front-end/timepay-front/src/App.tsx
  src/front-end/timepay-front/src/api/hooks/agency.ts
  src/front-end/timepay-front/src/api/hooks/user.ts
  src/front-end/timepay-front/src/api/request.ts
  src/front-end/timepay-front/src/api/urls.ts
  src/front-end/timepay-front/src/assets/images/icons/agency-user.svg
  src/front-end/timepay-front/src/components/MainFooter/MainFooter.tsx
  src/front-end/timepay-front/src/components/SimplePostCard/SimplePostCard.styles.tsx
  src/front-end/timepay-front/src/components/SimplePostCard/SimplePostCard.tsx
  src/front-end/timepay-front/src/pages/AgencySignInPage/AgencySignInPage.tsx
  src/front-end/timepay-front/src/pages/LoginPage/kakaoRedirectHandler.tsx
  src/front-end/timepay-front/src/pages/MyPage/MyPage.tsx
  src/front-end/timepay-front/src/pages/RegisterPage/RegisterEventPage.tsx
  src/front-end/timepay-front/src/pages/index.ts
  src/front-end/timepay-front/src/utils/paths.ts
Labels: ✨ feat

#259 앱 코드 위치 변경, 카카오 로그인 웹뷰 상에서 하도록 수정
  src/app/timepay_Android-master/app/build.gradle
  src/app/timepay_Android-master/app/proguard-rules.pro
  src/app/timepay_Android-master/app/src/androidTest/java/com/example/android_tutorial_kotlin/ExampleInstrumentedTest.kt
  src/app/timepay_Android-master/app/src/main/AndroidManifest.xml
  src/app/timepay_Android-master/app/src/main/java/com/example/android_tutorial_kotlin/MainActivity.kt
  src/app/timepay_Android-master/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  src/app/timepay_Android-master/app/src/main/res/drawable/ic_launcher_background.xml
  src/app/timepay_Android-master/app/src/main/res/drawable/timepay_launcher_background.xml
  src/app/timepay_Android-master/app/src/main/res/drawable/timepay_logo.png
  src/app/timepay_Android-master/app/src/main/res/drawable/timepay_logo2.png
  src/app/timepay_Android-master/app/src/main/res/layout/activity_main.xml
  src/app/timepay_Android-master/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  src/app/timepay_Android-master/app/src/main/res/mipmap-anydpi-v26/timepay_launcher.xml
  src/app/timepay_Android-master/app/src/main/res/mipmap-anydpi-v26/timepay_launcher_round.xml
  src/app/timepay_Android-master/app/src/main/res/mipmap-anydpi-v33/ic_launcher.xml
  src/app/timepay_Android-master/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  src/app/timepay_Android-master/app/src/main/res/mipmap-hdpi/timepay_launcher.png
  src/app/timepay_Android-master/app/src/main/res/mipmap-hdpi/timepay_launcher_foreground.png
  src/app/timepay_Android-master/app/src/main/res/mipmap-hdpi/timepay_launcher_round.png
  src/app/timepay_Android-master/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  src/app/timepay_Android-master/app/src/main/res/mipmap-mdpi/timepay_launcher.png
  src/app/timepay_Android-master/app/src/main/res/mipmap-mdpi/timepay_launcher_foreground.png
  src/app/timepay_Android-master/app/src/main/res/mipmap-mdpi/timepay_launcher_round.png
  src/app/timepay_Android-master/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  src/app/timepay_Android-master/app/src/main/res/mipmap-xhdpi/timepay_launcher.png
  src/app/timepay_Android-master/app/src/main/res/mipmap-xhdpi/timepay_launcher_foreground.png
  src/app/timepay_Android-master/app/src/main/res/mipmap-xhdpi/timepay_launcher_round.png
  src/app/timepay_Android-master/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  src/app/timepay_Android-master/app/src/main/res/mipmap-xxhdpi/timepay_launcher.png
  src/app/timepay_Android-master/app/src/main/res/mipmap-xxhdpi/timepay_launcher_foreground.png
  src/app/timepay_Android-master/app/src/main/res/mipmap-xxhdpi/timepay_launcher_round.png
  src/app/timepay_Android-master/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  src/app/timepay_Android-master/app/src/main/res/mipmap-xxxhdpi/timepay_launcher.png
  src/app/timepay_Android-master/app/src/main/res/mipmap-xxxhdpi/timepay_launcher_foreground.png
  src/app/timepay_Android-master/app/src/main/res/mipmap-xxxhdpi/timepay_launcher_round.png
  src/app/timepay_Android-master/app/src/main/res/values-night/themes.xml
  src/app/timepay_Android-master/app/src/main/res/values/colors.xml
  src/app/timepay_Android-master/app/src/main/res/values/strings.xml
  src/app/timepay_Android-master/app/src/main/res/values/themes.xml
  src/app/timepay_Android-master/app/src/main/res/xml/backup_rules.xml
  src/app/timepay_Android-master/app/src/main/res/xml/data_extraction_rules.xml
  src/app/timepay_Android-master/app/src/main/timepay_launcher-playstore.png
  src/app/timepay_Android-master/app/src/main/타임페이 커뮤니티-playstore.png
  src/app/timepay_Android-master/app/src/test/java/com/example/android_tutorial_kotlin/ExampleUnitTest.kt
  src/app/timepay_Android-master/build.gradle
  src/app/timepay_Android-master/gradle.properties
  src/app/timepay_Android-master/gradle/wrapper/gradle-wrapper.jar
  src/app/timepay_Android-master/gradle/wrapper/gradle-wrapper.properties
  src/app/timepay_Android-master/gradlew
  src/app/timepay_Android-master/gradlew.bat
  src/app/timepay_Android-master/hs_err_pid12204.log
  src/app/timepay_Android-master/hs_err_pid13008.log
  src/app/timepay_Android-master/hs_err_pid17676.log
  src/app/timepay_Android-master/hs_err_pid21672.log
  src/app/timepay_Android-master/hs_err_pid7032.log
  src/app/timepay_Android-master/replay_pid12204.log
  src/app/timepay_Android-master/settings.gradle
Labels: ✨ feat, 🔧 refactor

#264 [사용자]타임테이블 추가
  src/front-end/timepay-front/package.json
  src/front-end/timepay-front/src/components/TimeTable/TimeTable.style.tsx
  src/front-end/timepay-front/src/components/TimeTable/TimeTable.tsx
  src/front-end/timepay-front/src/components/TimeTable/index.ts
  src/front-end/timepay-front/src/pages/ActivityRecordPage/ActivityRecordPage.tsx
  src/front-end/timepay-front/src/styles/constants/colors.ts
  src/front-end/timepay-front/yarn.lock
Labels: 💄 design, ✨ feat

#266 홈화면 검색화면에 알림함 추가
  src/front-end/timepay-front/src/components/BaseLayout/BaseLayout.styles.tsx
  src/front-end/timepay-front/src/components/BaseLayout/BaseLayout.tsx
  src/front-end/timepay-front/src/components/SearchHeader/SearchHeader.styles.tsx
Labels: 💄 design, 🧶 chore

#269 [사용자] 개인 사용자 마이페이지, 내 정보 수정 화면 수정
  src/front-end/timepay-front/src/pages/MyEditPage/MyEditPage.tsx
  src/front-end/timepay-front/src/pages/MyPage/MyPage.tsx
Labels: 🧶 chore

#271 chore: 알림함 api 연결 수정, view 속성 바꾸는 api 추가
  src/front-end/timepay-front/src/api/hooks/push.ts
  src/front-end/timepay-front/src/api/interfaces/IPush.ts
  src/front-end/timepay-front/src/api/request.ts
  src/front-end/timepay-front/src/components/PushCollapse/PushCollapse.tsx
  src/front-end/timepay-front/src/pages/PushNotificationPage/PushNotificationPage.tsx
Labels: ✨ feat, 🧶 chore

#272 [사용자] 기관 회원 마이페이지 조회, 정보 수정 페이지 추가 및 기능 연결
  src/front-end/timepay-front/src/App.tsx
  src/front-end/timepay-front/src/api/hooks/agency.ts
  src/front-end/timepay-front/src/api/hooks/user.ts
  src/front-end/timepay-front/src/api/interfaces/IAgency.ts
  src/front-end/timepay-front/src/api/request.ts
  src/front-end/timepay-front/src/api/urls.ts
  src/front-end/timepay-front/src/pages/AgencyEditPage/AgencyEdit.styles.tsx
  src/front-end/timepay-front/src/pages/AgencyEditPage/AgencyEditPage.tsx
  src/front-end/timepay-front/src/pages/AgencyEditPage/index.ts
  src/front-end/timepay-front/src/pages/AgencySignInPage/AgencySignInPage.tsx
  src/front-end/timepay-front/src/pages/MyPage/MyPage.styles.tsx
  src/front-end/timepay-front/src/pages/MyPage/MyPage.tsx
  src/front-end/timepay-front/src/pages/index.ts
  src/front-end/timepay-front/src/utils/paths.ts
Labels: 💄 design, ✨ feat, 🧶 chore

#273 [사용자] 로그인 화면 스타일 수정, 기관 회원으로 가는 링크 버튼 추가
  src/front-end/timepay-front/src/api/hooks/user.ts
  src/front-end/timepay-front/src/api/interfaces/IUser.ts
  src/front-end/timepay-front/src/pages/LoginPage/Login.styles.ts
  src/front-end/timepay-front/src/pages/LoginPage/LoginPage.tsx
Labels: 💄 design, 🧶 chore

#275 [사용자] 헤더 순서 변경 및 게시글 작성 버튼 플로팅버튼변경
  src/front-end/timepay-front/src/assets/images/icons/modify-font-size-big.svg
  src/front-end/timepay-front/src/assets/images/icons/modify-font-size-small.svg
  src/front-end/timepay-front/src/components/BaseLayout/BaseLayout.styles.tsx
  src/front-end/timepay-front/src/components/BaseLayout/BaseLayout.tsx
  src/front-end/timepay-front/src/components/HomeHeader/HomeHeader.styles.tsx
  src/front-end/timepay-front/src/components/HomeHeader/HomeHeader.tsx
  src/front-end/timepay-front/src/components/MainFooter/MainFooter.styles.tsx
  src/front-end/timepay-front/src/components/MainFooter/MainFooter.tsx
  src/front-end/timepay-front/src/components/SearchHeader/SearchHeader.styles.tsx
Labels: 💄 design, 🧶 chore

#276 게시글 조회 화면 댓글 조회 api 연결
  src/front-end/timepay-front/src/api/hooks/board.ts
  src/front-end/timepay-front/src/api/hooks/comment.ts
  src/front-end/timepay-front/src/api/interfaces/IComment.ts
  src/front-end/timepay-front/src/api/interfaces/IPost.ts
  src/front-end/timepay-front/src/api/urls.ts
  src/front-end/timepay-front/src/components/post/Item.style.tsx
  src/front-end/timepay-front/src/components/post/Item.tsx
  src/front-end/timepay-front/src/pages/PostPage/PostPage.style.tsx
  src/front-end/timepay-front/src/pages/PostPage/PostPage.tsx
  src/front-end/timepay-front/src/pages/RegisterPage/RegisterRequestPage.tsx
Labels: ✨ feat, 🧶 chore

#277 [사용자] 게시글 조회 api 연결
  src/front-end/timepay-front/src/api/hooks/board.ts
  src/front-end/timepay-front/src/api/interfaces/IPost.ts
  src/front-end/timepay-front/src/components/SimplePostCard/SimplePostCard.tsx
  src/front-end/timepay-front/src/components/post/PostButton.tsx
  src/front-end/timepay-front/src/pages/PostPage/PostPage.style.tsx
  src/front-end/timepay-front/src/pages/PostPage/PostPage.tsx
Labels: ✨ feat

#279 [사용자] 검색화면 큰 글씨 버전 추가
  src/front-end/timepay-front/src/components/MainFooter/MainFooter.tsx
  src/front-end/timepay-front/src/components/PostStatusTag/PostStatusTag.styles.tsx
  src/front-end/timepay-front/src/components/PostStatusTag/PostStatusTag.tsx
  src/front-end/timepay-front/src/components/PostTypeTag/PostTypeTag.styles.tsx
  src/front-end/timepay-front/src/components/PostTypeTag/PostTypeTag.tsx
  src/front-end/timepay-front/src/components/SearchHeader/SearchHeader.styles.tsx
  src/front-end/timepay-front/src/components/SearchHeader/SearchHeader.tsx
  src/front-end/timepay-front/src/components/SimplePostCard/SimplePostCard.styles.tsx
  src/front-end/timepay-front/src/components/SimplePostCard/SimplePostCard.tsx
  src/front-end/timepay-front/src/index.css
  src/front-end/timepay-front/src/pages/SearchPage/SearchPage.styles.tsx
  src/front-end/timepay-front/src/pages/SearchPage/SearchPage.tsx
Labels: 💄 design, 🧶 chore

#281 design: 활동기록 큰 글씨 버전 추가, 게시글로 링크 추가
  src/front-end/timepay-front/src/components/ActivityCommentCard/ActivityCommentCard.styles.tsx
  src/front-end/timepay-front/src/components/ActivityCommentCard/ActivityCommentCard.tsx
  src/front-end/timepay-front/src/components/ActivityPostCard/ActivityPostCard.styles.tsx
  src/front-end/timepay-front/src/components/ActivityPostCard/ActivityPostCard.tsx
  src/front-end/timepay-front/src/components/AnotherUserProfileDrawer/AnotherUserProfileDrawer.tsx
  src/front-end/timepay-front/src/index.css
  src/front-end/timepay-front/src/pages/ActivityRecordPage/ActivityRecordPage.styles.tsx
  src/front-end/timepay-front/src/pages/ActivityRecordPage/ActivityRecordPage.tsx
  src/front-end/timepay-front/src/pages/PushNotificationPage/PushNotificationPage.tsx
  src/front-end/timepay-front/src/styles/constants/tabStyle.ts
Labels: 💄 design, 🧶 chore

#282 [사용자] 마이페이지 큰 글씨 버전 추가
  src/front-end/timepay-front/src/pages/MyPage/My.css
  src/front-end/timepay-front/src/pages/MyPage/MyPage.styles.tsx
  src/front-end/timepay-front/src/pages/MyPage/MyPage.tsx
Labels: 💄 design, 🧶 chore

#285 [사용자] 바로도움요청 화면 추가
  src/front-end/timepay-front/src/App.tsx
  src/front-end/timepay-front/src/api/hooks/user.ts
  src/front-end/timepay-front/src/api/interfaces/IAgency.ts
  src/front-end/timepay-front/src/api/interfaces/IUser.ts
  src/front-end/timepay-front/src/components/InstantActivityQRModal/InstantActivityQRModal.styles.tsx
  src/front-end/timepay-front/src/components/InstantActivityQRModal/InstantActivityQRModal.tsx
  src/front-end/timepay-front/src/components/InstantActivityQRModal/index.ts
  src/front-end/timepay-front/src/components/MainFooter/MainFooter.tsx
  src/front-end/timepay-front/src/index.css
  src/front-end/timepay-front/src/pages/AgencyEditPage/AgencyEditPage.tsx
  src/front-end/timepay-front/src/pages/InstantActivityPage/InstantActivityPage.styles.tsx
  src/front-end/timepay-front/src/pages/InstantActivityPage/InstantActivityPage.tsx
  src/front-end/timepay-front/src/pages/InstantActivityPage/index.ts
  src/front-end/timepay-front/src/pages/MyPage/MyPage.styles.tsx
  src/front-end/timepay-front/src/pages/MyPage/MyPage.tsx
  src/front-end/timepay-front/src/pages/index.ts
  src/front-end/timepay-front/src/utils/paths.ts
Labels: 💄 design, ✨ feat

#290 [사용자] 앱 코드에 콜백 추가 및 회원가입 시 앱에서 받아온 디바이스 토큰 보내기
  src/app/flutter/lib/main.dart
  src/app/flutter/pubspec.lock
  src/app/flutter/pubspec.yaml
  src/front-end/timepay-front/src/pages/JoinPage/JoinPage.tsx
  src/front-end/timepay-front/src/utils/device.ts
  src/front-end/timepay-front/src/utils/global.d.ts
Labels: ✨ feat, 🔧 refactor

#296 feat: 바로도움요청 일지 작성 api 연결
  src/front-end/timepay-front/src/api/hooks/instantMatching.ts
  src/front-end/timepay-front/src/api/interfaces/IInstantMatching.ts
  src/front-end/timepay-front/src/api/urls.ts
  src/front-end/timepay-front/src/pages/InstantActivityPage/InstantActivityPage.tsx
Labels: ✨ feat, 🧶 chore

#297 [사용자] 베이스 레이아웃 수정
  src/front-end/timepay-front/src/components/BaseLayout/BaseLayout.tsx
  src/front-end/timepay-front/src/components/MainFooter/MainFooter.tsx
  src/front-end/timepay-front/src/pages/LoginPage/kakaoRedirectHandler.tsx
  src/front-end/timepay-front/src/states/uiState.ts
Labels: 💄 design

#301 feat: 안드로이드 카메라, 저장소 접근
  src/app/flutter/android/app/src/main/AndroidManifest.xml
Labels: ✨ feat

#304 feat: 푸시 클릭 시 알림함 화면으로 이동
  src/app/flutter/lib/main.dart
Labels: ✨ feat

#306 [사용자]대리인 UI추가
  src/front-end/timepay-front/src/App.tsx
  src/front-end/timepay-front/src/api/interfaces/IApplicant.ts
  src/front-end/timepay-front/src/components/AgentModal/AgentModal.style.tsx
  src/front-end/timepay-front/src/components/AgentModal/AgentModal.tsx
  src/front-end/timepay-front/src/components/AgentModal/index.ts
  src/front-end/timepay-front/src/components/ApplicantModal/ApplicantModal.style.tsx
  src/front-end/timepay-front/src/components/ApplicantModal/ApplicantModal.tsx
  src/front-end/timepay-front/src/components/ApplicantModal/index.ts
  src/front-end/timepay-front/src/components/ApplicantReceivedModal/ApplicantReceivedModal.tsx
  src/front-end/timepay-front/src/components/ApplicantReceivedModal/ApplicantReceivedModalstyle.tsx
  src/front-end/timepay-front/src/components/ApplicantReceivedModal/index.ts
  src/front-end/timepay-front/src/index.css
  src/front-end/timepay-front/src/pages/AgentPage/AgentPage.style.tsx
  src/front-end/timepay-front/src/pages/AgentPage/AgentPage.tsx
  src/front-end/timepay-front/src/pages/AgentPage/index.ts
  src/front-end/timepay-front/src/pages/ApplicantPage/ApplicantPage.style.tsx
  src/front-end/timepay-front/src/pages/ApplicantPage/ApplicantPage.tsx
  src/front-end/timepay-front/src/pages/ApplicantPage/index.ts
  src/front-end/timepay-front/src/pages/MyPage/MyPage.tsx
  src/front-end/timepay-front/src/pages/index.ts
  src/front-end/timepay-front/src/utils/paths.ts
Labels: 💄 design

#311 [사용자] 게시글 등록 화면 & 게시글 삭제 수정
  src/front-end/timepay-front/src/api/interfaces/IPost.ts
  src/front-end/timepay-front/src/pages/PostPage/PostPage.style.tsx
  src/front-end/timepay-front/src/pages/PostPage/PostPage.tsx
  src/front-end/timepay-front/src/pages/RegisterPage/RegisterFreePage.style.tsx
  src/front-end/timepay-front/src/pages/RegisterPage/RegisterRequest.styles.tsx
  src/front-end/timepay-front/src/pages/RegisterPage/RegisterRequestPage.tsx
  src/front-end/timepay-front/src/pages/RegisterPage/RegisterServePage.tsx
Labels: 💄 design, 🧶 chore

#314 [사용자] 게시글 등록 화면
  src/front-end/timepay-front/src/pages/RegisterPage/RegisterFreePage.style.tsx
  src/front-end/timepay-front/src/pages/RegisterPage/RegisterRequestPage.tsx
Labels: 💄 design, 🧶 chore

#315 [사용자] 기부하기 게시글 목록 조회 화면, 기능 연결
  src/front-end/timepay-front/src/api/hooks/board.ts
  src/front-end/timepay-front/src/api/hooks/donation.ts
  src/front-end/timepay-front/src/api/interfaces/IDonation.ts
  src/front-end/timepay-front/src/api/interfaces/IPost.ts
  src/front-end/timepay-front/src/api/urls.ts
  src/front-end/timepay-front/src/components/PostStatusTag/PostStatusTag.tsx
  src/front-end/timepay-front/src/components/SearchHeader/SearchHeader.tsx
  src/front-end/timepay-front/src/components/SimplePostCard/SimplePostCard.styles.tsx
  src/front-end/timepay-front/src/components/SimplePostCard/SimplePostCard.tsx
  src/front-end/timepay-front/src/index.css
  src/front-end/timepay-front/src/pages/DonationBoardPage/DonationBoardPage.tsx
  src/front-end/timepay-front/src/pages/DonationBoardWritePage/DonationBoardWritePage.tsx
  src/front-end/timepay-front/src/pages/SearchPage/SearchPage.tsx
  src/front-end/timepay-front/src/utils/board.ts
Labels: 💄 design, ✨ feat, 🧶 chore

#319 fix:디바이스 토큰 업데이트 순서 변경
  src/front-end/timepay-front/src/pages/LoginPage/kakaoRedirectHandler.tsx
Labels: 🐍 fix

#320 [사용자] 댓글 등록 api, 댓글 삭제 api 연결
  src/front-end/timepay-front/src/api/hooks/comment.ts
  src/front-end/timepay-front/src/api/interfaces/IComment.ts
  src/front-end/timepay-front/src/api/urls.ts
  src/front-end/timepay-front/src/components/post/Item.style.tsx
  src/front-end/timepay-front/src/components/post/Item.tsx
  src/front-end/timepay-front/src/pages/PostPage/PostPage.tsx
Labels: ✨ feat

#335 [사용자] 게시글 상태 변경 api 연결
  src/front-end/timepay-front/src/api/hooks/board.ts
  src/front-end/timepay-front/src/api/interfaces/IPost.ts
  src/front-end/timepay-front/src/components/PostStatusTag/PostStatusTag.tsx
  src/front-end/timepay-front/src/components/post/ApplicantButton.tsx
  src/front-end/timepay-front/src/components/post/PostButton.style.tsx
  src/front-end/timepay-front/src/components/post/PostButton.tsx
  src/front-end/timepay-front/src/pages/PostPage/PostPage.style.tsx
  src/front-end/timepay-front/src/pages/PostPage/PostPage.tsx
  src/front-end/timepay-front/src/utils/board.ts
Labels: ✨ feat

#337 [사용자] 기부하기 게시글 수정, 삭제, 작성자 여부 추가
  src/front-end/timepay-front/src/App.tsx
  src/front-end/timepay-front/src/api/hooks/donation.ts
  src/front-end/timepay-front/src/api/interfaces/IAgency.ts
  src/front-end/timepay-front/src/api/interfaces/IDonation.ts
  src/front-end/timepay-front/src/api/urls.ts
  src/front-end/timepay-front/src/components/SimplePostCard/SimplePostCard.tsx
  src/front-end/timepay-front/src/pages/DonationBoardEditPage/DonationBoardEditPage.styles.tsx
  src/front-end/timepay-front/src/pages/DonationBoardEditPage/DonationBoardEditPage.tsx
  src/front-end/timepay-front/src/pages/DonationBoardEditPage/index.ts
  src/front-end/timepay-front/src/pages/DonationBoardPage/DonationBoardPage.style.tsx
  src/front-end/timepay-front/src/pages/DonationBoardPage/DonationBoardPage.tsx
  src/front-end/timepay-front/src/pages/DonationBoardWritePage/DonationBoardWritePage.tsx
  src/front-end/timepay-front/src/pages/index.ts
Labels: 💄 design, ✨ feat, 🧶 chore

#339 [사용자] 타유저프로필 화면 기능 연결
  src/front-end/timepay-front/src/api/hooks/user.ts
  src/front-end/timepay-front/src/components/AnotherUserProfileDrawer/AnotherUserProfileDrawer.styles.tsx
  src/front-end/timepay-front/src/components/AnotherUserProfileDrawer/AnotherUserProfileDrawer.tsx
  src/front-end/timepay-front/src/pages/DonationBoardPage/DonationBoardPage.tsx
Labels: 💄 design, ✨ feat, 🧶 chore

#340 [사용자] 댓글 무한 호출 에러 수정, 봉사활동 지급 게시글 등록, 자동 매칭 게시글 등록 추가
  src/front-end/timepay-front/src/api/hooks/board.ts
  src/front-end/timepay-front/src/api/hooks/comment.ts
  src/front-end/timepay-front/src/api/hooks/reports.ts
  src/front-end/timepay-front/src/api/interfaces/IPost.ts
  src/front-end/timepay-front/src/components/post/Item.tsx
  src/front-end/timepay-front/src/pages/PostPage/PostPage.style.tsx
  src/front-end/timepay-front/src/pages/PostPage/PostPage.tsx
  src/front-end/timepay-front/src/pages/RegisterPage/RegisterRequest.styles.tsx
  src/front-end/timepay-front/src/pages/RegisterPage/RegisterRequestPage.tsx
Labels: 🧶 chore, 🐍 fix

#350 [사용자] 봉사활동 인증서 지급/ 내 봉사활동 메뉴 기능 연결
  src/front-end/timepay-front/src/api/hooks/agency.ts
  src/front-end/timepay-front/src/api/hooks/user.ts
  src/front-end/timepay-front/src/api/interfaces/ICommon.ts
  src/front-end/timepay-front/src/api/interfaces/IVolunteer.ts
  src/front-end/timepay-front/src/api/urls.ts
  src/front-end/timepay-front/src/components/post/PostButton.style.tsx
  src/front-end/timepay-front/src/components/post/PostButton.tsx
  src/front-end/timepay-front/src/pages/MyVolunteerPage/MyVolunteerPage.tsx
  src/front-end/timepay-front/src/pages/VolunteerCertificationPaymentPage/VolunteerCertificationPaymentPage.tsx
Labels: ✨ feat

#351 [관리자] 기관 관리, 게시글 관리 일부 수정
  src/front-end/timepay-admin/src/api/interfaces/IAgency.ts
  src/front-end/timepay-admin/src/components/AgencyTable/AgencyTable.tsx
  src/front-end/timepay-admin/src/components/PostTable/PostTable.tsx
  src/front-end/timepay-admin/src/states/agencySearchState.ts
Labels: 🧶 chore

#355 [사용자] 댓글 작성자가 누구인지에 따른 댓글 UI 디자인
  src/front-end/timepay-front/src/components/post/Item.style.tsx
  src/front-end/timepay-front/src/components/post/Item.tsx
  src/front-end/timepay-front/src/pages/PostPage/PostPage.tsx
Labels: 💄 design, ✨ feat

#360 [사용자] 큰 글씨 버전 추가
  src/front-end/timepay-front/src/components/PushCollapse/PushCollapse.styles.tsx
  src/front-end/timepay-front/src/components/PushCollapse/PushCollapse.tsx
  src/front-end/timepay-front/src/components/SimplePostCard/SimplePostCard.styles.tsx
  src/front-end/timepay-front/src/pages/DonationBoardPage/DonationBoardPage.style.tsx
  src/front-end/timepay-front/src/pages/DonationBoardPage/DonationBoardPage.tsx
  src/front-end/timepay-front/src/pages/MyEditPage/MyEdit.styles.tsx
  src/front-end/timepay-front/src/pages/MyEditPage/MyEditPage.tsx
  src/front-end/timepay-front/src/pages/MyVolunteerPage/MyVolunteerPage.styles.tsx
  src/front-end/timepay-front/src/pages/MyVolunteerPage/MyVolunteerPage.tsx
Labels: 💄 design

#364 [사용자] 선정하기 모달, 도움요청 게시글 등록 시 타임페이량 안내 및 등록 불가 처리
  src/front-end/timepay-front/src/components/post/PostButton.tsx
  src/front-end/timepay-front/src/index.css
  src/front-end/timepay-front/src/pages/RegisterPage/RegisterRequestPage.tsx
Labels: 💄 design, 🧶 chore

#366 [사용자] 기관 활동기록 화면에 모금 현황 화면 추가 및 api 연결
  src/front-end/timepay-front/src/api/hooks/agency.ts
  src/front-end/timepay-front/src/api/interfaces/IDonation.ts
  src/front-end/timepay-front/src/api/interfaces/IPost.ts
  src/front-end/timepay-front/src/api/urls.ts
  src/front-end/timepay-front/src/components/ActivityDonationCard/ActivityDonationCard.styles.tsx
  src/front-end/timepay-front/src/components/ActivityDonationCard/ActivityDonationCard.tsx
  src/front-end/timepay-front/src/components/ActivityDonationCard/index.ts
  src/front-end/timepay-front/src/components/SimplePostCard/SimplePostCard.tsx
  src/front-end/timepay-front/src/pages/ActivityRecordPage/ActivityRecordPage.tsx
Labels: ✨ feat, 🧶 chore

#367 feat: 회원가입 시 이용약관, 개인정보처리방침 모달 추가
  src/front-end/timepay-front/src/components/PolicyModal/PolicyModal.tsx
  src/front-end/timepay-front/src/components/PolicyModal/index.tsx
  src/front-end/timepay-front/src/pages/JoinPage/Join.styles.tsx
  src/front-end/timepay-front/src/pages/JoinPage/JoinPage.tsx
Labels: ✨ feat, 🧶 chore

#369 feat: 앱 시작시 카메라, 폴더 접근 권한 허용 알림 추가
  src/app/flutter/android/app/src/main/AndroidManifest.xml
  src/app/flutter/lib/main.dart
  src/app/flutter/pubspec.lock
  src/app/flutter/pubspec.yaml
  src/app/flutter/windows/flutter/generated_plugin_registrant.cc
  src/app/flutter/windows/flutter/generated_plugins.cmake
Labels: ✨ feat

#370 feat: 앱 세로모드 고정, 상태바 숨김 처리
  src/app/flutter/lib/main.dart
Labels: 💄 design

#372 fix: 게시글 조회 화면 - 지원 댓글 작성 안되는 오류 수정
  src/front-end/timepay-front/src/components/post/Item.tsx
  src/front-end/timepay-front/src/pages/PostPage/PostPage.tsx
Labels: 🐍 fix

#373 fix: 댓글 수정, 삭제 버튼 노출 오류 수정
  src/front-end/timepay-front/src/components/post/Item.tsx
Labels: 🐍 fix

#374 chore: 게시글 조회화면 관심기능 삭제
  src/front-end/timepay-front/src/pages/PostPage/PostPage.style.tsx
  src/front-end/timepay-front/src/pages/PostPage/PostPage.tsx
Labels: 🧶 chore
