Repository kookmin-sw/capstone-2023-09, pull requests merged in 2023-04, with the labels that each got.

#80 [사용자] 활동 기록 화면 UI 개발
  src/front-end/timepay-front/src/App.tsx
  src/front-end/timepay-front/src/api/interfaces/IComment.ts
  src/front-end/timepay-front/src/components/ActivityCommentCard/ActivityCommentCard.styles.tsx
  src/front-end/timepay-front/src/components/ActivityCommentCard/ActivityCommentCard.tsx
  src/front-end/timepay-front/src/components/ActivityCommentCard/index.ts
  src/front-end/timepay-front/src/components/ActivityPostCard/ActivityPostCard.styles.tsx
  src/front-end/timepay-front/src/components/ActivityPostCard/ActivityPostCard.tsx
  src/front-end/timepay-front/src/components/ActivityPostCard/index.ts
  src/front-end/timepay-front/src/pages/ActivityRecordPage/ActivityRecordPage.styles.tsx
  src/front-end/timepay-front/src/pages/ActivityRecordPage/ActivityRecordPage.tsx
  src/front-end/timepay-front/src/pages/ActivityRecordPage/index.ts
  src/front-end/timepay-front/src/pages/index.ts
  src/front-end/timepay-front/src/utils/paths.ts
Labels: 💄 design

#81 [사용자] 타 유저 프로필 조회 화면 UI 개발
  src/front-end/timepay-front/src/components/AnotherUserProfileDrawer/AnotherUserProfileDrawer.styles.tsx
  src/front-end/timepay-front/src/components/AnotherUserProfileDrawer/AnotherUserProfileDrawer.tsx
  src/front-end/timepay-front/src/components/AnotherUserProfileDrawer/index.ts
  src/front-end/timepay-front/src/components/BaseLayout/BaseLayout.styles.tsx
  src/front-end/timepay-front/src/pages/ActivityRecordPage/ActivityRecordPage.tsx
  src/front-end/timepay-front/src/styles/constants/tabStyle.ts
Labels: 💄 design

#84 공통코드 - api 관련 설정 및 예시 추가
  src/front-end/timepay-admin/package.json
  src/front-end/timepay-admin/src/api/hooks/comment.ts
  src/front-end/timepay-admin/src/api/hooks/login.ts
  src/front-end/timepay-admin/src/api/interfaces/IAdmin.ts
  src/front-end/timepay-admin/src/api/interfaces/ILogin.ts
  src/front-end/timepay-admin/src/api/request.ts
  src/front-end/timepay-admin/src/api/urls.ts
  src/front-end/timepay-admin/src/index.tsx
  src/front-end/timepay-admin/src/pages/CommentManagement/CommentManagementPage.tsx
  src/front-end/timepay-admin/src/pages/Login/LoginPage.tsx
  src/front-end/timepay-admin/src/utils/token.ts
  src/front-end/timepay-admin/yarn.lock
  src/front-end/timepay-front/package.json
  src/front-end/timepay-front/src/api/request.ts
  src/front-end/timepay-front/src/api/urls.ts
  src/front-end/timepay-front/src/hooks/post.ts
  src/front-end/timepay-front/src/index.tsx
  src/front-end/timepay-front/src/utils/token.ts
  src/front-end/timepay-front/yarn.lock
Labels: ✨ feat

#79 [사용자] 게시글 조회 화면 UI 개발
  src/front-end/timepay-front/src/App.tsx
  src/front-end/timepay-front/src/assets/images/icons/like_click.svg
  src/front-end/timepay-front/src/assets/images/icons/like_default.svg
  src/front-end/timepay-front/src/components/BaseLayout/BaseLayout.tsx
  src/front-end/timepay-front/src/components/SimplePostCard/SimplePostCard.tsx
  src/front-end/timepay-front/src/components/post/Comment.tsx
  src/front-end/timepay-front/src/components/post/InputText.tsx
  src/front-end/timepay-front/src/components/post/Item.style.tsx
  src/front-end/timepay-front/src/components/post/Item.tsx
  src/front-end/timepay-front/src/components/post/PostButton.style.tsx
  src/front-end/timepay-front/src/components/post/PostButton.tsx
  src/front-end/timepay-front/src/pages/HomePage/HomePage.tsx
  src/front-end/timepay-front/src/pages/PostPage/PostEditPage.style.tsx
  src/front-end/timepay-front/src/pages/PostPage/PostEditPage.tsx
  src/front-end/timepay-front/src/pages/PostPage/PostPage.style.tsx
  src/front-end/timepay-front/src/pages/PostPage/PostPage.tsx
  src/front-end/timepay-front/src/pages/index.ts
  src/front-end/timepay-front/src/services/index.ts
  src/front-end/timepay-front/src/styles/constants/colors.ts
  src/front-end/timepay-front/src/utils/paths.ts
Labels: 💄 design, ✨ feat

#94 [관리자, 사용자] api 공통함수 수정 - Bearer, axios delete
  src/front-end/timepay-admin/src/api/request.ts
  src/front-end/timepay-front/src/api/request.ts
Labels: 🧶 chore, 🐍 fix

#99 [관리자] 푸시 관리 메뉴 기능 연결
  src/front-end/timepay-admin/src/api/hooks/notification.ts
  src/front-end/timepay-admin/src/api/interfaces/ICommon.ts
  src/front-end/timepay-admin/src/api/interfaces/INotification.ts
  src/front-end/timepay-admin/src/api/urls.ts
  src/front-end/timepay-admin/src/components/PushAddModal/PushAddModal.style.tsx
  src/front-end/timepay-admin/src/components/PushAddModal/PushAddModal.tsx
  src/front-end/timepay-admin/src/components/PushDeleteModal/PushDeleteModal.tsx
  src/front-end/timepay-admin/src/components/PushDetailModal/PushDetailModal.tsx
  src/front-end/timepay-admin/src/components/PushSearchForm/PushSearchForm.tsx
  src/front-end/timepay-admin/src/components/PushTable/PushTable.tsx
  src/front-end/timepay-admin/src/pages/PushManagement/PushManagementPage.tsx
  src/front-end/timepay-admin/src/states/pushSearchState.ts
Labels: ✨ feat, 🎨 style, 🔧 refactor

#89 [관리자] 회원 관리 - 활동 목록, 정보 수정 모달 업데이트
  src/front-end/timepay-admin/src/pages/UserManagement/Data/DONGDATA.ts
  src/front-end/timepay-admin/src/pages/UserManagement/Data/GUDATA.ts
  src/front-end/timepay-admin/src/pages/UserManagement/Data/SIDATA.ts
  src/front-end/timepay-admin/src/pages/UserManagement/UserManagement.styles.tsx
  src/front-end/timepay-admin/src/pages/UserManagement/UserManagementPage.tsx
  src/front-end/timepay-admin/src/pages/UserManagement/blackListModal.tsx
  src/front-end/timepay-admin/src/pages/UserManagement/delUserModal.tsx
  src/front-end/timepay-admin/src/pages/UserManagement/detailModal.tsx
  src/front-end/timepay-admin/src/pages/UserManagement/editModal.tsx
  src/front-end/timepay-admin/src/pages/UserManagement/mainTable.tsx
  src/front-end/timepay-admin/src/pages/UserManagement/profileImageModal.tsx
  src/front-end/timepay-admin/src/pages/UserManagement/searchForm.tsx
  src/front-end/timepay-front/src/pages/JoinPage/JoinPage.tsx
Labels: ✨ feat

#111 프록시 주소를 aws 서버로 api url 수정
  src/front-end/timepay-admin/package.json
  src/front-end/timepay-admin/src/api/request.ts
  src/front-end/timepay-front/package.json
  src/front-end/timepay-front/src/api/request.ts
Labels: 🧶 chore

#112 공지 조회, 등록 api 변경으로 인한 변경
  src/front-end/timepay-admin/src/api/hooks/notification.ts
  src/front-end/timepay-admin/src/api/interfaces/INotification.ts
  src/front-end/timepay-admin/src/components/PushDeleteModal/PushDeleteModal.tsx
  src/front-end/timepay-admin/src/components/PushTable/PushTable.tsx
Labels: 🧶 chore

#132 [관리자] 페이지네이션 기능 추가
  src/front-end/timepay-admin/src/api/hooks/comment.ts
  src/front-end/timepay-admin/src/components/CommentTable/CommentTable.tsx
  src/front-end/timepay-admin/src/components/PushTable/PushTable.tsx
  src/front-end/timepay-admin/src/states/commentSearchState.ts
  src/front-end/timepay-admin/src/states/pushSearchState.ts
  src/front-end/timepay-admin/src/utils/pagination.ts
Labels: ✨ feat, 🔧 refactor

#131 [사용자] 전체 알림 화면에 공지사항 조회 api 연결
  src/front-end/timepay-front/src/api/hooks/push.ts
  src/front-end/timepay-front/src/api/interfaces/ICommon.ts
  src/front-end/timepay-front/src/api/interfaces/IPush.ts
  src/front-end/timepay-front/src/api/urls.ts
  src/front-end/timepay-front/src/components/PushCollapse/PushCollapse.styles.tsx
  src/front-end/timepay-front/src/components/PushCollapse/PushCollapse.tsx
  src/front-end/timepay-front/src/pages/PushNotificationPage/PushNotificationPage.tsx
  src/front-end/timepay-front/src/styles/constants/colors.ts
  src/front-end/timepay-front/src/styles/constants/tabStyle.ts
Labels: 💄 design, ✨ feat, 🧶 chore, 🔧 refactor

#113 [관리자] 로그인후 비밀번호 변경 및 로그아웃 추가
  src/front-end/timepay-admin/src/api/hooks/login.ts
  src/front-end/timepay-admin/src/api/hooks/passwordChange.ts
  src/front-end/timepay-admin/src/api/interfaces/IPasswordChange.ts
  src/front-end/timepay-admin/src/api/urls.ts
  src/front-end/timepay-admin/src/components/AdminAdd/AdminAdd.tsx
  src/front-end/timepay-admin/src/components/BaseLayout/BaseLayout.styles.tsx
  src/front-end/timepay-admin/src/components/BaseLayout/BaseLayout.tsx
  src/front-end/timepay-admin/src/pages/Login/LoginPage.tsx
  src/front-end/timepay-admin/src/pages/PasswordEdit/PasswordEditPage.tsx
Labels: 💄 design, ✨ feat

#133 [관리자] 관리자 관리 기능 연결
  src/front-end/timepay-admin/src/api/hooks/admin.ts
  src/front-end/timepay-admin/src/api/interfaces/IAdmin.ts
  src/front-end/timepay-admin/src/api/urls.ts
  src/front-end/timepay-admin/src/components/AdminAdd/AdminAdd.style.tsx
  src/front-end/timepay-admin/src/components/AdminAdd/AdminAdd.tsx
  src/front-end/timepay-admin/src/components/AdminMainTable/AdminMainTable.style.tsx
  src/front-end/timepay-admin/src/components/AdminMainTable/AdminMainTable.tsx
  src/front-end/timepay-admin/src/components/EditableCell/AdminEditableCell.tsx
  src/front-end/timepay-admin/src/interfaces/AdminItem.ts
  src/front-end/timepay-admin/src/styles/constants/colors.ts
Labels: 💄 design, ✨ feat, 🔧 refactor

#143 빌드 전 세부사항 수정
  src/front-end/timepay-front/src/pages/ActivityRecordPage/ActivityRecordPage.tsx
  src/front-end/timepay-front/src/pages/MyPage/My.css
  src/front-end/timepay-front/src/pages/MyPage/MyPage.tsx
  src/front-end/timepay-front/src/utils/paths.ts
Labels: 🧶 chore

#142 [사용자] 문의화면 api 연결 & 게시글 조회화면 UI 수정 & isFooter 수정
  src/front-end/timepay-front/src/api/hooks/inquiry.ts
  src/front-end/timepay-front/src/api/hooks/register.ts
  src/front-end/timepay-front/src/api/interfaces/IPost.ts
  src/front-end/timepay-front/src/api/interfaces/IQna.ts
  src/front-end/timepay-front/src/api/urls.ts
  src/front-end/timepay-front/src/components/BaseLayout/BaseLayout.tsx
  src/front-end/timepay-front/src/components/PostStatusTag/PostStatusTag.tsx
  src/front-end/timepay-front/src/components/post/Item.style.tsx
  src/front-end/timepay-front/src/components/post/Item.tsx
  src/front-end/timepay-front/src/components/post/PostButton.style.tsx
  src/front-end/timepay-front/src/components/post/PostButton.tsx
  src/front-end/timepay-front/src/components/qna/QnaList.tsx
  src/front-end/timepay-front/src/pages/PostPage/PostPage.style.tsx
  src/front-end/timepay-front/src/pages/PostPage/PostPage.tsx
  src/front-end/timepay-front/src/pages/QnaPage/QnaListPage.tsx
  src/front-end/timepay-front/src/pages/QnaPage/QnaRegisterPage.tsx
  src/front-end/timepay-front/src/pages/RegisterPage/RegisterFreePage.style.tsx
  src/front-end/timepay-front/src/pages/RegisterPage/RegisterFreePage.tsx
  src/front-end/timepay-front/src/pages/RegisterPage/RegisterRequestPage.tsx
  src/front-end/timepay-front/src/utils/paths.ts
Labels: 💄 design, ✨ feat

#147 [사용자] 회원가입 화면 CSS 수정
  src/front-end/timepay-front/src/components/qna/QnaList.style.tsx
  src/front-end/timepay-front/src/pages/JoinPage/JoinPage.tsx
Labels: 🧶 chore
