Repository kookmin-sw/capstone-2023-09, pull requests merged in 2023-03, with the labels that each got.

#54 [관리자] #52, #44 회원 조회 / 회원 수정 / 문의 관리 api 개발
  src/back-end/timepay/build.gradle
  src/back-end/timepay/docker-compose.yml
  src/back-end/timepay/src/main/java/com/capstone/timepay/controller/admin/InquiryManageController.java
  src/back-end/timepay/src/main/java/com/capstone/timepay/controller/admin/UserManageController.java
  src/back-end/timepay/src/main/java/com/capstone/timepay/controller/admin/request/inquiry/InquiryAnswerRequest.java
  src/back-end/timepay/src/main/java/com/capstone/timepay/controller/admin/request/userManage/UserInfoUpdateRequest.java
  src/back-end/timepay/src/main/java/com/capstone/timepay/controller/admin/response/inquiry/AdminAnswerResponse.java
  src/back-end/timepay/src/main/java/com/capstone/timepay/controller/admin/response/inquiry/InquiryDetailResponse.java
  src/back-end/timepay/src/main/java/com/capstone/timepay/controller/admin/response/inquiry/InquiryResponse.java
  src/back-end/timepay/src/main/java/com/capstone/timepay/controller/admin/response/userManage/BoardActivityDto.java
  src/back-end/timepay/src/main/java/com/capstone/timepay/controller/admin/response/userManage/CommentActivityDto.java
  src/back-end/timepay/src/main/java/com/capstone/timepay/controller/admin/response/userManage/MainResponse.java
  src/back-end/timepay/src/main/java/com/capstone/timepay/controller/admin/response/userManage/ReceivedReportDto.java
  src/back-end/timepay/src/main/java/com/capstone/timepay/controller/admin/response/userManage/UserProfileResponse.java
  src/back-end/timepay/src/main/java/com/capstone/timepay/controller/board/HomeController.java
  src/back-end/timepay/src/main/java/com/capstone/timepay/controller/board/request/Test.java
  src/back-end/timepay/src/main/java/com/capstone/timepay/controller/board/response/Test.java
  src/back-end/timepay/src/main/java/com/capstone/timepay/domain/BaseTimeEntity.java
  src/back-end/timepay/src/main/java/com/capstone/timepay/domain/admin/Admin.java
  src/back-end/timepay/src/main/java/com/capstone/timepay/domain/inquiry/Inquiry.java
  src/back-end/timepay/src/main/java/com/capstone/timepay/domain/inquiry/InquiryRepository.java
  src/back-end/timepay/src/main/java/com/capstone/timepay/domain/inquiryAnswer/InquiryAnswer.java
  src/back-end/timepay/src/main/java/com/capstone/timepay/domain/inquiryAnswer/InquiryAnswerRepository.java
  src/back-end/timepay/src/main/java/com/capstone/timepay/domain/user/User.java
  src/back-end/timepay/src/main/java/com/capstone/timepay/domain/user/UserRepository.java
  src/back-end/timepay/src/main/java/com/capstone/timepay/service/admin/InquiryManagerService.java
  src/back-end/timepay/src/main/java/com/capstone/timepay/service/admin/UserManageService.java
  src/back-end/timepay/src/main/java/com/capstone/timepay/service/admin/dto/InquiryAnswerDto.java
  src/back-end/timepay/src/main/java/com/capstone/timepay/service/admin/dto/UserUpdateDto.java
  src/back-end/timepay/src/main/resources/application.yml
Labels: ✨ feat, 💻 development

#60 [사용자] 게시글 작성 화면 개발
  src/front-end/timepay-front/src/App.tsx
  src/front-end/timepay-front/src/components/BaseLayout/BaseLayout.tsx
  src/front-end/timepay-front/src/components/MainFooter/MainFooter.tsx
  src/front-end/timepay-front/src/components/register/ImageUpload.tsx
  src/front-end/timepay-front/src/components/register/KoDatePicker.tsx
  src/front-end/timepay-front/src/components/register/TagSelect.tsx
  src/front-end/timepay-front/src/components/register/TimeSelect.tsx
  src/front-end/timepay-front/src/pages/RegisterPage/RegisterFreePage.style.tsx
  src/front-end/timepay-front/src/pages/RegisterPage/RegisterFreePage.tsx
  src/front-end/timepay-front/src/pages/RegisterPage/RegisterRequestPage.tsx
  src/front-end/timepay-front/src/pages/RegisterPage/RegisterServePage.tsx
  src/front-end/timepay-front/src/pages/index.ts
  src/front-end/timepay-front/src/states/register.ts
  src/front-end/timepay-front/src/styles/constants/colors.ts
  src/front-end/timepay-front/src/utils/paths.ts
  src/front-end/timepay-front/yarn.lock
Labels: 💄 design, ✨ feat

#61 [관리자]관리자 관리 화면 UI 추가
  src/front-end/timepay-admin/package.json
  src/front-end/timepay-admin/src/App.tsx
  src/front-end/timepay-admin/src/components/AdminAdd/AdminAdd.style.tsx
  src/front-end/timepay-admin/src/components/AdminAdd/AdminAdd.tsx
  src/front-end/timepay-admin/src/components/AdminAdd/index.ts
  src/front-end/timepay-admin/src/components/AdminMainTable/AdminMainTable.style.tsx
  src/front-end/timepay-admin/src/components/AdminMainTable/AdminMainTable.tsx
  src/front-end/timepay-admin/src/components/AdminMainTable/index.ts
  src/front-end/timepay-admin/src/components/EditableCell/AdminEditableCell.tsx
  src/front-end/timepay-admin/src/interfaces/AdminItem.ts
  src/front-end/timepay-admin/src/pages/AdminManagement/AdminManagementPage.style.tsx
  src/front-end/timepay-admin/src/pages/AdminManagement/AdminManagementPage.tsx
  src/front-end/timepay-admin/src/pages/AdminManagement/index.ts
  src/front-end/timepay-admin/src/pages/index.ts
  src/front-end/timepay-admin/yarn.lock
Labels: 💄 design

#77 [관리자] 게시글 검색값 축소 및 테이블 컬럼 추가
  src/front-end/timepay-admin/src/components/PostSearchForm/PostSearchForm.styles.tsx
  src/front-end/timepay-admin/src/components/PostSearchForm/PostSearchForm.tsx
  src/front-end/timepay-admin/src/components/PostTable/PostTable.tsx
Labels: 🧶 chore

#75 [관리자]로그인 ,비밀번호 변경 화면 UI 개발
  src/front-end/timepay-admin/src/App.tsx
  src/front-end/timepay-admin/src/assets/images/timepay-logo.svg
  src/front-end/timepay-admin/src/components/BaseLayout/BaseLayout.tsx
  src/front-end/timepay-admin/src/pages/Login/Login.styles.tsx
  src/front-end/timepay-admin/src/pages/Login/LoginPage.tsx
  src/front-end/timepay-admin/src/pages/Login/index.ts
  src/front-end/timepay-admin/src/pages/PasswordEdit/PasswordEditPage.styles.tsx
  src/front-end/timepay-admin/src/pages/PasswordEdit/PasswordEditPage.tsx
  src/front-end/timepay-admin/src/pages/PasswordEdit/index.ts
  src/front-end/timepay-admin/src/pages/index.ts
  src/front-end/timepay-admin/src/styles/constants/colors.ts
  src/front-end/timepay-admin/src/utils/paths.ts
  src/front-end/timepay-admin/yarn.lock
Labels: 💄 design

#71 [사용자] 검색 화면 UI 개발
  src/front-end/timepay-front/src/components/BaseLayout/BaseLayout.styles.tsx
  src/front-end/timepay-front/src/components/BaseLayout/BaseLayout.tsx
  src/front-end/timepay-front/src/components/HomeHeader/HomeHeader.styles.tsx
  src/front-end/timepay-front/src/components/MainHeader/MainHeader.styles.tsx
  src/front-end/timepay-front/src/components/SearchHeader/SearchHeader.styles.tsx
  src/front-end/timepay-front/src/components/SearchHeader/SearchHeader.tsx
  src/front-end/timepay-front/src/components/SearchHeader/index.ts
  src/front-end/timepay-front/src/index.css
  src/front-end/timepay-front/src/pages/SearchPage/SearchPage.tsx
  src/front-end/timepay-front/src/styles/constants/colors.ts
Labels: 💄 design

#70 [사용자] 문의 화면 개발
  src/front-end/timepay-front/src/App.tsx
  src/front-end/timepay-front/src/api/interfaces/IQna.ts
  src/front-end/timepay-front/src/components/BaseLayout/BaseLayout.tsx
  src/front-end/timepay-front/src/components/qna/QnaList.style.tsx
  src/front-end/timepay-front/src/components/qna/QnaList.tsx
  src/front-end/timepay-front/src/components/register/TagSelect.tsx
  src/front-end/timepay-front/src/pages/QnaPage/QnaDetailPage.style.tsx
  src/front-end/timepay-front/src/pages/QnaPage/QnaDetailPage.tsx
  src/front-end/timepay-front/src/pages/QnaPage/QnaListPage.tsx
  src/front-end/timepay-front/src/pages/QnaPage/QnaRegisterPage.tsx
  src/front-end/timepay-front/src/pages/index.ts
  src/front-end/timepay-front/src/states/register.ts
  src/front-end/timepay-front/src/utils/paths.ts
Labels: 💄 design, ✨ feat

#78 [사용자] 알림함 화면 UI 개발
  src/front-end/timepay-front/src/App.tsx
  src/front-end/timepay-front/src/api/interfaces/IPush.ts
  src/front-end/timepay-front/src/components/HomeHeader/HomeHeader.tsx
  src/front-end/timepay-front/src/components/MainHeader/MainHeader.styles.tsx
  src/front-end/timepay-front/src/components/PushCollapse/PushCollapse.styles.tsx
  src/front-end/timepay-front/src/components/PushCollapse/PushCollapse.tsx
  src/front-end/timepay-front/src/components/PushCollapse/index.ts
  src/front-end/timepay-front/src/pages/PushNotificationPage/PushNotificationPage.tsx
  src/front-end/timepay-front/src/pages/PushNotificationPage/index.ts
  src/front-end/timepay-front/src/pages/index.ts
  src/front-end/timepay-front/src/styles/constants/colors.ts
  src/front-end/timepay-front/src/styles/constants/tabStyle.ts
  src/front-end/timepay-front/src/utils/paths.ts
Labels: 💄 design
